# Generated by Django 4.2.1 on 2023-05-31 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("autho", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
