version: "3.8"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  producer:
    build: ./producer
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./producer:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis

  consumer:
    build: ./consumer
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./consumer:/usr/src/app/
    ports:
      - 8001:8001
    depends_on:
      - redis
      - producer
volumes:
  redis:
    driver: local
